version: "3"

networks:
  app:

services:
  server:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./dockerfiles/config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app

  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "9000:9000"
    volumes:
      - ./php:/var/www/html
    networks:
      - app
